---
title: "ANA 515 Assignment 1"
author: "Larissa Andono"
date: "6/5/2022"
output:
  html_document:
    theme: lumen

---

```{r,  include = FALSE}

install.packages("tidyverse")
install.packages("readr")
install.packages("knitr")
install.packages("bslib")

```


```{r,  include = FALSE}

library(tidyverse)
library(readr)
library(knitr)
library(bslib)

```


``` {r, include = FALSE}
url<- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv" 
gun_deaths<-read_csv(url)

```

```{r, include = FALSE}
library(dplyr)
youth <- gun_deaths %>% 
  filter(age <= 65)

```

```{r, include = FALSE}
summary (youth)
```


```{r, echo = FALSE}
#This next chunk is inline code. Inline code puts the text with the output of the function in my document.
```

We have data about `r nrow(gun_deaths)` individuals killed by guns. Only 
`r nrow(gun_deaths) - nrow(youth)` are older than 65. The distribution of the remainder is shown below: 

``` {r, echo = FALSE}
#This next code chunk will make a plot in our output doc
```


# Gun death by age
```{r youth-dist, echo = FALSE}
#the distribution of the age variable from the youth dataset
library (ggplot2)
youth %>% 
  ggplot(aes(age)) + 
  geom_freqpoly(binwidth = 1)

```

# Gun death by race
```{r, echo = FALSE}
#the distribution of youth by race.

youth %>%
  ggplot(aes(fct_infreq(race) %>% fct_rev()))  +
  geom_bar() + coord_flip() +
  labs(x="Victim race")
```
